---
- hosts: localhost
  become: yes
  tasks:
  - name: Run the equivalent of "apt-get update"
    apt:
      update_cache: yes

  - name: Install git
    apt:
      name: git

  - name: Install gcc
    apt:
      name: gcc

  - name: Install build-essential
    apt:
      name: build-essential

  - name: Install unzip
    apt:
      name: unzip

